apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
type: application
version: v1.0.0
appVersion: v1.16.2
dependencies:
- name: cert-manager
  version: v1.17.2
  repository: https://charts.jetstack.io