apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: monitoring
  labels:
    app.kubernetes.io/name: homepage


data:
  kubernetes.yaml: |
    mode: cluster

  settings.yaml: |
    title: "Please take a number"

    headerStyle: boxedWidgets # clean, boxed, underlined
    background: 
      image: https://cdn.zekkei-japan.jp/datas/cache/images/2024/05/17/800x533_ea1e9d427fb5664c32c517a73e421e58_64b1b1f8a9202dd4951b40f0417ae834bebb3585.jpg
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 50 # 0-100
    theme: dark
    color: gray
    
    # Equal heights for service boxes
    useEqualHeights: true
    
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
      provider: duckduckgo

    # You can choose from the following styles for docker or k8s status, site monitor and ping: dot or basic
    statusStyle: "dot"

    layout:
      Quick:
        header: false
        style: column
      Access:
        header: false
        style: column
      Calendar:
        header: false
        style: column
      Infra and Network:
        header: true
        style: row
        columns: 4
      Media:
        header: true
        style: row
        columns: 4
      Monitoring:
        header: true
        style: row 
        columns: 4 
      Servarr:
        header: true
        style: row 
        columns: 4
      Access and Services:
        header: true
        style: row
        columns: 4
        
    providers:
      longhorn:
        url: https://longhorn.pawked.com

  custom.css: ""

  # layout.yaml: ""

  custom.js: ""

  bookmarks.yaml: |
    - Quick:
        - YouTube:
            - icon: youtube.svg
              href: https://youtube.com
              description: Video Monopoly       
    - Access:
        - Homepage:
            - icon: homepage.png
              href: https://gethomepage.dev/main/
              description: Homepage Documentation                
        - Dashboard Icons:
            - icon: github.svg
              href: https://github.com/walkxcode/dashboard-icons
              description: Icon Repository    

  services.yaml: |
    - Calendar:
      - Media Calendar:
          widget:
            type: calendar
            firstDayInWeek: sunday
            view: monthly
            maxEvents: 10
            showTime: true
            timezone: Asia/Tokyo
            integrations:
              - type: sonarr
                service_group: Servarr
                service_name: Sonarr
                color: teal
                params:
                  unmonitored: false
              - type: radarr
                service_group: Servarr 
                service_name: Radarr
                color: yellow
                params:
                  unmonitored: false
              - type: lidarr
                service_group: Servarr
                service_name: Lidarr
                color: green
                params:
                  unmonitored: false

    - Infra and Network:
      - Deluge:
          href: https://deluge.pawked.com
          icon: deluge.png
          siteMonitor: https://deluge.pawked.com
          widget:
            type: deluge
            url: https://deluge.pawked.com
            password: "{{HOMEPAGE_VAR_DELUGE_PASSWORD}}"
            enableLeechProgress: true # optional, defaults to false    
      - Pihole:
          href: http://192.168.1.48/admin
          icon: pi-hole.svg
          siteMonitor: http://192.168.1.148
          widget:
            type: pihole
            url: http://192.168.1.148
            version: 6 # required if running v6 or higher, defaults to 5
            key: "{{HOMEPAGE_VAR_PIHOLE_PASSWORD}}"
      - Truenas:
          href: http://192.168.1.122
          icon: truenas-core.svg
          widget:
            type: truenas
            url: http://192.168.1.122
            key: "{{HOMEPAGE_VAR_TRUENAS_KEY}}"
            enablePools: true
            nasType: core

    - Servarr:
      - Radarr:
          href: https://radarr.pawked.com
          icon: radarr.svg
          siteMonitor: https://radarr.pawked.com
          widget:
            type: radarr
            url: https://radarr.pawked.com
            key: "{{HOMEPAGE_VAR_RADARR_KEY}}"
            enableQueue: true # optional, defaults to false
      - Sonarr:
          href: https://sonarr.pawked.com
          icon: sonarr.svg
          siteMonitor: https://sonarr.pawked.com
          widget:
            type: sonarr
            url: https://sonarr.pawked.com
            key: "{{HOMEPAGE_VAR_SONARR_KEY}}"
            enableQueue: true # optional, defaults to false
      - Lidarr:
          href: https://lidarr.pawked.com
          icon: lidarr.svg
          siteMonitor: https://lidarr.pawked.com
          widget:
            type: lidarr
            url: https://lidarr.pawked.com
            key: "{{HOMEPAGE_VAR_LIDARR_KEY}}"

  widgets.yaml: |
    - datetime:
        text_size: 3xl # Valid text sizes are 4xl, 3xl, 2xl, xl, md, sm, xs.
        format:
          dateStyle: short
          timeStyle: short
          hour12: true
    - openmeteo:
        label: Azumino
        latitude: 36.2882
        longitude: 137.887
        timezone: Asia/Tokyo # optional
        units: metric # or imperial
        cache: 5 # Time in minutes to cache API responses, to stay within limits
        format:
          maximumFractionDigits: 1
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: true
    - search:
        provider: duckduckgo
        target: _blank

  docker.yaml: ""