apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-vars-externalsecret 
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: homepage-vars-secret
  dataFrom:
  - extract:
      key: homepage
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None