apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: truenas-gotify-adapter-externalsecret
  namespace: truenas-gotify-adapter
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: truenas-gotify-adapter-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: truenas-gotify-adapter
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None