apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: <external secret name>-externalsecret   # arbitrary name of this externalsecret resource
  namespace: <target namespace>                 # the namespace to put the secret in
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: <kubernetes secret name>-secrets      # the name of the secret that's going to be made in kubernetes in the defined namespace
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: <vault secret-name>                  # the name of the vault secret to pull data from
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None