apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gotify-externalsecret
  namespace: gotify
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gotify-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: gotify
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None