apiVersion: apps/v1
kind: Deployment
metadata:
  name: truenas-graphite-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: truenas-graphite-exporter
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: truenas-graphite-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: truenas-graphite-exporter
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9108"
        prometheus.io/scrape: "true"
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: truenas-graphite-exporter
          image: prom/graphite-exporter:v0.16.0
          imagePullPolicy: Always
          args:
            - --graphite.mapping-config=/tmp/graphite_mapping.yaml
            # - --graphite.mapping-strict-match
            # - --log.level=debug
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
          ports:
            - containerPort: 9109
              name: graphite-tcp
              protocol: TCP
            - containerPort: 9109
              name: graphite-udp
              protocol: UDP
            - containerPort: 9108
              name: prometheus
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: config-volume
      volumes:
      - name: config-volume
        configMap:
          defaultMode: 420
          name: truenas-graphite-exporter