---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-postgresql-svc
  labels:
    app: nextcloud-postgresql
spec:
  ports:
  - port: 5432
    name: tcp-postgres
  selector:
    app: nextcloud-postgresql