apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-ngx-externalsecret
  namespace: paperless
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: paperless-ngx-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: paperless-ngx
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-rclone-externalsecret
  namespace: paperless
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: paperless-rclone-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: paperless-rclone
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None