apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-externalsecret
  namespace: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: authentik
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None