prometheus-smartctl-exporter:

  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: Exists
      effect: NoSchedule

  serviceMonitor:
    enabled: false

  podAnnotations: 
    prometheus.io/scrape: "true"
    prometheus.io/port: "9633"
    prometheus.io/path: "/metrics"