apiVersion: v2
name: nextcloud
description: A Helm chart for nextcloud
type: application
version: 1.1.0
appVersion: 31.0.8
dependencies:
  - name: nextcloud
    version: 8.0.1
    repository: https://nextcloud.github.io/helm/