---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  labels:
    longhornvolume: backup-test
    # recurring-job-group.longhorn.io/default: enabled
    # setting.longhorn.io/remove-snapshots-during-filesystem-trim: ignored
    # setting.longhorn.io/replica-auto-balance: ignored
    # setting.longhorn.io/snapshot-data-integrity: ignored
    # recurring-job.longhorn.io/statefulset-vol-0: enabled
  name: backup-test
  namespace: longhorn-system
spec:
  numberOfReplicas: 2
  disableFrontend: false
  engineImage: longhornio/longhorn-engine:v1.8.1
  # fromBackup: "nfs://nfs.pawked.com:/mnt/slime/k8s/longhorn-backups?backup=backup-5e5294236fce471f&volume=uptime-kuma"
  frontend: blockdev
  size: "1073741824"
  staleReplicaTimeout: 30
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-test
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '2'
      staleReplicaTimeout: '30'
    volumeHandle: backup-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  volumeName: backup-test
  storageClassName: longhorn-static