apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-db-externalsecret
  namespace: nextcloud
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nextcloud-db-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: nextcloud-db-secret
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None