apiVersion: v2
name: longhorn
description: A Helm chart for Longhorn
type: application
version: v1.0.0
appVersion: v1.8.0
dependencies:
  - name: longhorn
    version: 1.8.1
    repository: https://charts.longhorn.io