longhorn:

  # global:
    ## Allow scheduling on control plane for replication
    # tolerations:
    # - key: "node-role.kubernetes.io/control-plane"
    #   operator: "Exists"
    #   effect: "NoSchedule"
      
  # longhornUI:
    # nodeSelector:
      # node-role.kubernetes.io/worker: "true"

  ## needed for argocd install
  preUpgradeChecker:
  # -- Setting that allows Longhorn to perform pre-upgrade checks. Disable this setting when installing Longhorn using Argo CD or other GitOps solutions.
    jobEnabled: false

  defaultSettings:
    defaultDataPath: "/var/lib/longhorn" # same as default, but i'm just marking it down here
    defaultReplicaCount: 2

  defaultBackupStore:
    backupTarget: "nfs://nfs.pawked.com:/mnt/slime/k8s/longhorn-backups"  # Backup to TrueNAS NFS share

  persistence:
    defaultClass: false  # keep truenas-nfs as the default storage class for now
    defaultClassReplicaCount: 2 # I only have 2 nodes running longhorn

  ingress:
    enabled: true
    ingressClassName: "internal"
    host: "longhorn.pawked.com"

  longhornVolumes:  # volumes can also be declared here if necessary
    ## Just a test volume
  #   test-volume:
  #     namespace: media
  #     replicas: 2
  #     size: "257949696" # needs quotes
  #     dataLocality: best-effort
  #     fromBackup: ""
  #     accessMode: rwo
  #     backingImage: ""
  #     encrypted: false
  #     frontend: blockdev
  #     staleReplicaTimeout: 30