apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redmine-secret
  namespace: redmine
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: redmine-secret
  dataFrom:
  - extract:
      key: redmine-secret
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None