---
apiVersion: v2
name: external-dns
description: A Helm chart for external-dns
type: application
version: 1.0.0
appVersion: "0.15.1"
dependencies:
- name: external-dns
  version: 1.16.1
  repository: https://kubernetes-sigs.github.io/external-dns/