apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    root_url = https://monitoring.jwschman.com
    serve_from_sub_path = true

    [users]
    allow_sign_up = false
    allow_org_create = false
    auto_assign_org = true
    auto_assign_org_role = Viewer
    viewers_can_edit = false
    editors_can_admin = false

    [auth]
    disable_login_form = true
    disable_signout_menu = true

    [auth.anonymous]
    enabled = true
    org_role = Viewer
    enable_api = false

    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/dashboard.json
    min_refresh_interval = 30s

    [branding]
    app_title = "HomeLabo Dashboard"