apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden-externalsecret
  namespace: linkwarden
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: linkwarden-secrets
  dataFrom:
  - extract:
      key: linkwarden
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None