apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pawked-wildcard-cert
  namespace: cert-manager
spec:
  secretName: pawked-wildcard-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "*.pawked.com"
  - "pawked.com" 
