---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-externalsecret
  namespace: redis
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: redis-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: redis
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None