redis:
  auth:
    existingSecret: redis-secrets
    existingSecretPasswordKey: password
  architecture: standalone
  metrics:
    enabled: true
  
  master:
    persistence:
      enabled: false
    resourcesPreset: "micro"
    # service settings are defaults but included for reference
    service:
      type: ClusterIP
      portNames:
        redis: "tcp-redis"
      ports:
        redis: 6379