apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: freshrss
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
      - name: freshrss
        image: freshrss/freshrss:1.26.3
        imagePullPolicy: IfNotPresent
        env:
        # for Authentik support
        # refer to https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect-Authentik.html
        - name: OIDC_ENABLED
          value: "1"
        - name: OIDC_PROVIDER_METADATA_URL
          value: https://auth.pawked.com/application/o/freshrss/.well-known/openid-configuration
        - name: OIDC_X_FORWARDED_HEADERS
          value: X-Forwarded-Port X-Forwarded-Proto X-Forwarded-Host
        - name: OIDC_SCOPES
          value: openid email profile
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: freshrss-secrets
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: freshrss-secrets
              key: OIDC_CLIENT_SECRET
        # Freshrss Env
        - name: TZ
          value: Asia/Tokyo
        - name: CRON_MIN
          value: 13,43
        ## For initial install - I wound up not using this
        # - name: FRESHRSS_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: freshrss-secrets
        #       key: FRESHRSS_USER
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /var/www/FreshRSS/data
        - name: extensions
          mountPath: /var/www/FreshRSS/extensions
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          tcpSocket:
            port: 80
        readinessProbe:
          tcpSocket:
            port: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: freshrss-data
      - name: extensions
        persistentVolumeClaim:
          claimName: freshrss-extensions