apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: freshrss-externalsecret
  namespace: freshrss
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: freshrss-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: freshrss
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None