apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-externalsecret
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret # needs to be argocd-secret for argo to pull from
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: argocd
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None