apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-repo-externalsecret
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-github-repo
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
        annotations:
          managed-by: argocd.argoproj.io
  dataFrom:
  - extract:
      key: argocd-github-repo
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None