apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-mariadb-secret
  namespace: wordpress
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wordpress-mariadb-secret
  dataFrom:
  - extract:
      key: wordpress-mariadb-secret
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None